### PR TITLE
Git/week1

### PR DESCRIPTION
**Pull request by AkoAyukngat**
I just finished my homework to make 3 files containing my 2 best food and 3 countries i have visited.

### CODE REVIEW

**Comment by martamatos** [comment]
I can see that you didn't have a smooth start with the description of eru commit (it's empty), but the last 3 commits are just fine :)

In which branch were you when you created the branch git/week1? In the master branch or in the git_example branch? Something tells me you were in the git_example branch ;)

**Comment by AkoAyukngat** [comment]
Hi Martha, I could not detect which branch i was when i gave the command.
Maybe i did not do it
correctly. Should i have started by typing "git branch git/week1" ? then
later i checkout to see which branch I am on ?

**Comment by martamatos** [comment]
First you do `git status`, that will show you in which branch you are (the one in green). If you are on master it's all good, you can go ahead and create your homework branch (git/week1 in this case). If you are not on master, you should go to master (`git checkout master`), and once you are on master you can create your homework branch.
Does this make sense?

**Comment by AkoAyukngat** [comment]
Yes, it makes much sense :)

**Pull request merged**
